app/__init__.py
from flask import Flask

app = Flask(__name__)


from app import routes

from routes import classification

app.register_blueprint(classification)

app/routes.py
import os
from collections import defaultdict
import csv
from ast import literal_eval

from flask import Blueprint, render_template, request, redirect, url_for, jsonify
from werkzeug.utils import secure_filename
import numpy
from PIL import Image
from skimage import io, color
from sklearn.neighbors import NearestNeighbors
from colormath.color_objects import LabColor, sRGBColor, XYZColor, HSLColor
from colormath.color_conversions import convert_color

UPLOAD_FOLDER = os.path.dirname(os.path.abspath(__file__)) + "/static/imgs/temp"
CSV_FOLDER = os.path.dirname(os.path.abspath(__file__)) + "/static/csv/master.csv"
ALLOWED_EXTENSIONS = set(['png', 'jpg', 'jpeg'])
image_size = (304, 228)

flower_dictionary = defaultdict(dict)

classification = Blueprint('classification', __name__, url_prefix='/classification',
                    template_folder='templates', static_folder='static')


@classification.route("/", methods=["GET", "POST"])
def default():
    return redirect(url_for("classification.main_application"))

@classification.route("/upload", methods=["POST", "GET"])
def main_application():
    process = request.args.get("process")
    if process == "submit":
        distances, indices = submit()
        return render_template("index.html", process="upload", distances=", ".join(map(str, distances)), indices=", ".join(map(str, indices)))
    if request.method == "POST":
        file = request.files['file']
        if file:
            filename = secure_filename(file.filename)
            file_path = os.path.join(UPLOAD_FOLDER, filename)
            file.save(file_path)
            img = Image.open(file_path)
            img.thumbnail(image_size, Image.ANTIALIAS)
            img.save(file_path)
            return render_template("index.html", process="primary", file_path=filename)
    return render_template("index.html", process="upload", distances=None, indices=None)


@classification.route("/get_coordinates_color", methods=["GET"])
def get_image():
    x = float(request.args.get("x"))
    y = float(request.args.get("y"))
    filename = request.args.get("filename").split("/")[-1]
    process = request.args.get("process")
    file_path = os.path.join(UPLOAD_FOLDER, filename)
    im = Image.open(file_path)
    rgb_im = im.convert('RGB')

    r, g, b = rgb_im.getpixel((x, y))
    rgb = sRGBColor(r, g, b)
    lab = convert_color(rgb, LabColor, target_illuminant='d50')
    xyz = convert_color(rgb, XYZColor, target_illuminant='d50')
    hsi = convert_color(rgb, HSLColor)
    flower_dictionary[filename]["{}_RGB".format(process)] = (r, g, b)
    flower_dictionary[filename]["{}_LAB".format(process)] = (lab.lab_l, lab.lab_a, lab.lab_b)
    flower_dictionary[filename]["{}_XYZ".format(process)] = (xyz.xyz_x, xyz.xyz_y, xyz.xyz_z)
    flower_dictionary[filename]["{}_HSI".format(process)] = (hsi.hsl_h, hsi.hsl_s, hsi.hsl_l)
    return jsonify({"RGB": (r, g, b)})


@classification.route("/counter", methods=["GET"])
def save_count():
    filename = request.args.get("filename").split("/")[-1]
    count = int(request.args.get("count"))
    flower_dictionary[filename]["count"] = count
    return jsonify({"RGB": 0})

@classification.route("/picker", methods=["GET"])
def second_image():
    filename = request.args.get("filename")
    process = request.args.get("process")
    return render_template("index.html", process=process, file_path=filename)

@classification.route("/count", methods=["GET"])
def petal_count():
    filename = request.args.get("filename")
    process = request.args.get("process")
    return render_template("index.html", process=process, file_path=filename)

@classification.route("/stem_color", methods=["GET"])
def stem_color():
    filename = request.args.get("filename")
    process = request.args.get("process")
    return render_template("index.html", process=process, file_path=filename)


def submit():
    filename = request.args.get("filename").split("/")[-1]
    flower_dict = flower_dictionary[filename]
    line = [filename]
    nparry = []
    with open(CSV_FOLDER) as csvfile:
        reader = csv.DictReader(csvfile)
        for row in reader:
            temp = []
            count = float(row['count'])
            stem = literal_eval(row['stem_color_LAB'])
            primary = literal_eval(row['primary_LAB'])
            secondary = literal_eval(row['secondary_LAB'])
            temp.append(count)
            temp.extend(stem)
            temp.extend(primary)
            temp.extend(secondary)
            nparry.append(temp)

    uploaded_point = []
    count = int(flower_dict.get('count'))
    stem = flower_dict.get('stem_color_LAB')
    primary = flower_dict.get('primary_LAB')
    secondary = flower_dict.get('secondary_LAB')
    uploaded_point.append(count)
    uploaded_point.extend(stem)
    uploaded_point.extend(primary)
    uploaded_point.extend(secondary)
    np_array = numpy.array(nparry)
    nneighbors = 3 if len(np_array) >= 3 else len(np_array)
    nbrs = NearestNeighbors().fit(np_array)
    distances, indices = nbrs.kneighbors(uploaded_point, nneighbors, True)
    keys = ['count', 'stem_color_RGB', 'primary_RGB', 'secondary_RGB',
            'stem_color_XYZ', 'primary_XYZ', 'secondary_XYZ',
            'stem_color_LAB', 'primary_LAB', 'secondary_LAB',
            'stem_color_HSI', 'primary_HSI', 'secondary_HSI']
    line.extend([flower_dict.get(key) for key in keys])
    writer = csv.writer(open(CSV_FOLDER, 'a'))
    writer.writerow(line)

    return distances, indices

app/views/__init__.py
__author__ = 'adriel'

app/templates/base.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title>Flower Classification</title>
    {% block head %}{% endblock %}
</head>
<body>
    {% block body %}{% endblock %}
</body>
<script type="text/javascript">
    {% block script %}{% endblock %}
</script>
</html>

app/templates/index.html
{% extends "base.html" %}
{% block head %}
        <link href="{{ url_for('static', filename='css/bootstrap.css') }}" rel="stylesheet" type="text/css" media="all">
        <link href="{{ url_for('static', filename='css/specifics.css') }}" rel="stylesheet" type="text/css" media="all">
        <link href="{{ url_for('static', filename='css/bootstrap.min.css') }}" rel="stylesheet" type="text/css" media="all">
        <link href="{{ url_for('static', filename='css/bootstrap-theme.css') }}" rel="stylesheet" type="text/css" media="all">
        <link href="{{ url_for('static', filename='css/bootstrap-theme.min.css') }}" rel="stylesheet" type="text/css" media="all">
        <script src="{{ url_for('static', filename='js/jquery-2.1.3.min.js') }}"></script>
        <script src="{{ url_for('static', filename='js/bootstrap.js') }}"></script>
        <script src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>
{% endblock %}
{% block body %}
<div class="clean_center">
  <p class="lead">This is a simple application that provides human-assisted flower classification</p>
  {% if process == "upload" %}
      <div class="panel panel-default">
        <div class="panel-heading"><strong>Upload Files</strong></div>
          {% if distances %}
            <div><strong>Previous Upload kNN</strong></div>
            <p>Distances</p>
            <p>{{distances}}</p>
            <p>Indices</p>
            <p>{{indices}}</p>
          {% endif %}
        <div class="panel-body">

          <!-- Standar Form -->
          <h4>Select files from your computer</h4>
          <form action="" method="post" enctype="multipart/form-data" id="js-upload-form">
            <div class="form-inline">
              <div class="form-group">
                <input type="file" name="file" id="js-upload-files" multiple>
              </div>
              <button type="submit" class="btn btn-sm btn-primary" id="js-upload-submit">Upload file</button>
            </div>
          </form>
        </div>
      </div>
  {% elif process == "primary" %}
      <p>Primary Petal Color</p>
      <canvas id="chosen_color" width="200" height="60"></canvas>
      <img value="{{ process }}" src="{{ url_for('static', filename='imgs/temp/' + file_path) }}" id="flower" style="width:304px;height:228px">
      <a id="next" class="btn btn-sm btn-primary" href="{{ url_for('classification.second_image', filename=file_path, process="secondary") }}">Next</a>
  {% elif process == "secondary" %}
      <p>Secondary Petal Color</p>
      <canvas id="chosen_color" width="200" height="60"></canvas>
      <img value="{{ process }}" src="{{ url_for('static', filename='imgs/temp/' + file_path) }}" id="flower" style="width:304px;height:228px">
      <a id="next" class="btn btn-sm btn-primary" href="{{ url_for('classification.petal_count', filename=file_path, process="count") }}">Next</a>
  {% elif process == "count" %}
      <p>Petal Count</p>
        <form>
          <select class="btn btn-sm" id="selector">
            {% for i in range(40) %}
                <option value="{{ i }}" selected="selected">{{ i }}</option>
            {% endfor %}
          </select>
        </form>
      <img value="{{ process }}" src="{{ url_for('static', filename='imgs/temp/' + file_path) }}" style="width:304px;height:228px">
      <a id="next" class="btn btn-sm btn-primary" href="{{ url_for('classification.stem_color', filename=file_path, process="stem_color") }}">Next</a>
  {% elif process == "stem_color" %}
      <p>Stem Color</p>
      <canvas id="chosen_color" width="200" height="60"></canvas>
      <img value="{{ process }}" src="{{ url_for('static', filename='imgs/temp/' + file_path) }}" id="flower" style="width:304px;height:228px">
      <a id="next" class="btn btn-sm btn-primary" href="{{ url_for('classification.main_application', filename=file_path, process="submit") }}">Submit</a>
  {% endif %}
</div>
{% endblock %}

{% block script %}
    $( "#flower" ).click(function(e) {
        var offset = $(this).offset();
        var filename = $(this).attr("src");
        var process = $(this).attr("value");
        var x = e.clientX - offset.left;
        var y = e.clientY - offset.top;
        $.ajax({
                url: "{{ url_for('classification.get_image') }}",
                type: 'get',
                dataType: 'json',
                data: {
                    x: x,
                    y: y,
                    filename: filename,
                    process: process,
                }, success:function(data) {
                var example = document.getElementById('chosen_color');
                var context = example.getContext('2d');
                var r = data['RGB'][0].toString()
                var g = data['RGB'][1].toString()
                var b = data['RGB'][2].toString()
                context.fillStyle = "rgb(" + r + "," + g + "," + b + ")";
                context.fillRect(0, 0, 50, 50);
    }
        });
    });

    $("#selector").change(function() {
        var process = $("img").attr("value");
        var count = $( "#selector option:selected" ).text();;
        var filename =  $("img").attr("src");
        $.ajax({
                url: "{{ url_for('classification.save_count') }}",
                type: 'get',
                dataType: 'json',
                data: {
                    filename: filename,
                    process: process,
                    count: count,
                }, success:function(data) {

    }
        });
    });
{% endblock %}